/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvillena;

/**
 *
 * @author alumno
 */
public class Pagos extends javax.swing.JFrame {

    /**
     * Creates new form Pagos
     */
    public Pagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PagoconTarjeta1 = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        Aceptamos1 = new javax.swing.JLabel();
        ImgTarjetas1 = new javax.swing.JLabel();
        NombreTitular1 = new javax.swing.JLabel();
        NumeroTarjeta2 = new javax.swing.JLabel();
        CVV3 = new javax.swing.JLabel();
        FechaCaducidad4 = new javax.swing.JLabel();
        EscribirNombre1 = new javax.swing.JTextField();
        EscribirNumero2 = new javax.swing.JTextField();
        EscribirCodigo3 = new javax.swing.JTextField();
        EscribirDia4 = new javax.swing.JTextField();
        EscribirMes5 = new javax.swing.JTextField();
        Mensaje1 = new javax.swing.JLabel();
        OtrosMetoPago1 = new javax.swing.JButton();
        ConfCompra2 = new javax.swing.JButton();
        ImgTarjeta2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PagoconTarjeta1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PagoconTarjeta1.setText("Pago con Tarjeta");

        Aceptamos1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Aceptamos1.setText("Aceptamos:");

        ImgTarjetas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gvillena/visaaaaaaaaaaaaaa (1).png"))); // NOI18N

        NombreTitular1.setText("Nombre del Titular");

        NumeroTarjeta2.setText("Numero de la Tarjeta");

        CVV3.setText("CVV (Codigo de seguridad)");

        FechaCaducidad4.setText("Fecha de caducidad de la tarjeta");

        EscribirNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirNombre1ActionPerformed(evt);
            }
        });

        EscribirNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirNumero2ActionPerformed(evt);
            }
        });

        EscribirCodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirCodigo3ActionPerformed(evt);
            }
        });

        Mensaje1.setBackground(new java.awt.Color(0, 102, 255));
        Mensaje1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mensaje1.setForeground(new java.awt.Color(0, 51, 204));
        Mensaje1.setText("Confirm your order of 32,66 $ by clicking the button \"Confirm my order\"");

        OtrosMetoPago1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OtrosMetoPago1.setText("OTROS MÉTODOS DE PAGO");
        OtrosMetoPago1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtrosMetoPago1ActionPerformed(evt);
            }
        });

        ConfCompra2.setBackground(new java.awt.Color(0, 204, 255));
        ConfCompra2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ConfCompra2.setForeground(new java.awt.Color(255, 255, 255));
        ConfCompra2.setText("CONFIRMAR MI PEDIDO");

        ImgTarjeta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gvillena/ttttttttttttttttttttttttt (4).png"))); // NOI18N

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(OtrosMetoPago1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfCompra2)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Aceptamos1)
                            .addComponent(FechaCaducidad4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImgTarjetas1)
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CVV3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NumeroTarjeta2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NombreTitular1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(EscribirDia4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EscribirMes5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EscribirNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EscribirNombre1)
                                .addComponent(EscribirCodigo3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(ImgTarjeta2)
                        .addGap(63, 63, 63))))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Mensaje1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Aceptamos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImgTarjetas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreTitular1)
                            .addComponent(EscribirNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroTarjeta2)
                            .addComponent(EscribirNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CVV3)
                            .addComponent(EscribirCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(ImgTarjeta2)))
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscribirDia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaCaducidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EscribirMes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Mensaje1)
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OtrosMetoPago1)
                    .addComponent(ConfCompra2))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PagoconTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(PagoconTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EscribirNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirNombre1ActionPerformed

    private void EscribirCodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirCodigo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirCodigo3ActionPerformed

    private void EscribirNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirNumero2ActionPerformed

    private void OtrosMetoPago1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtrosMetoPago1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtrosMetoPago1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aceptamos1;
    private javax.swing.JLabel CVV3;
    private javax.swing.JButton ConfCompra2;
    private javax.swing.JTextField EscribirCodigo3;
    private javax.swing.JTextField EscribirDia4;
    private javax.swing.JTextField EscribirMes5;
    private javax.swing.JTextField EscribirNombre1;
    private javax.swing.JTextField EscribirNumero2;
    private javax.swing.JLabel FechaCaducidad4;
    private javax.swing.JLabel ImgTarjeta2;
    private javax.swing.JLabel ImgTarjetas1;
    private javax.swing.JLabel Mensaje1;
    private javax.swing.JLabel NombreTitular1;
    private javax.swing.JLabel NumeroTarjeta2;
    private javax.swing.JButton OtrosMetoPago1;
    private javax.swing.JLabel PagoconTarjeta1;
    private javax.swing.JPanel PanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
